### PR TITLE
Register UbikLoadPack Video Streaming plugin to JMeter-Plugins

### PR DESCRIPTION
**Pull request by ubikloadpack**
Hello @undera ,

This PR is to register our UbikLoadPack Video Streaming plugin so that it's available through jmeter-plugins-manager.
We think we have provided required elements, but let us know if anything is missing.

Kudos to all your OSS work for the JMeter community.

Thanks
Regards

### CODE REVIEW

**Comment by undera** [comment]
Looks like you forgot to change the descriptor...

**Comment by ubikloadpack** [comment]
> Looks like you forgot to change the descriptor...

Bad copy paste, fixed. Sorry

**Comment by ubikloadpack** [comment]
Thanks for merging.
What is the delay for plugin to appear on jmeter-plugins.org ? 

Thank you

**Comment by undera** [comment]
~30 mins

**Comment by ubikloadpack** [comment]
Thanks, it's available now in JMeter through plugins-manager, but does not appears on website yet when searching for it.

Regards

**Comment by undera** [comment]
Probably it was your browser cache at the moment. It works for me now.

**Comment by ubikloadpack** [comment]
Yes it works now.
Thanks

**Pull request merged**
