### PR TITLE
Fix webdriver bundle

### PR DESCRIPTION
**Pull request by pmouawad**
Hello,
This fixes the issue with Wedriver package on Windows as reported on google groups.

Regards
Philippe M. from UbikLoadPack Team

### CODE REVIEW

**Comment by undera** [comment]
Thanks!

**Comment by pmouawad** [comment]
Hello @undera ,
Thanks for merging.
What is needed to have the change live ?
I have just tested now, the change is at:
https://jmeter-plugins.org/repo/

But when I use jmeter-plugins it doesn't show the change nor downloads the additional jars.

Thanks

**Comment by undera** [comment]
Have you tried re-installing the plugin? It should help with latest version of plugins manager.
I have also fixed the "platform" library name in plugin descriptor.

**Comment by pmouawad** [comment]
Hi @undera ,
I have upgrade for both jars the jna one is ok , but it seems this one returns 404:

https://search.maven.org/remotecontent?filepath=/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar

But I don't know where to find this platform-3.5.2.jar although  it exists:
http://repo1.maven.org/maven2/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar

Is it possible in json to set this:

http://repo1.maven.org/maven2/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar

Thanks

**Comment by undera** [comment]
The real problem is an extra slash in your URL before `/net/java`. Changing it to `net/java` fixes it. I have committed the change, please try again in like 10 mins from now.

**Pull request merged**
