### PR TITLE
Added HTTP2 v2.0.1

### PR DESCRIPTION
**Pull request by RicardoPoleo**
Added release for the HTTP2 v2.0.1 with improvements and fixes for max buffer size.

### CODE REVIEW

**Comment by undera** [comment]
Note the failed CI: JSON structure is invalid

**Comment by undera** [comment]
Somehow, your PR has a lot of unrelated changes. Please make sure it only contains something that relates to your change.

**Comment by undera** [comment]
Please roll back anything that you did not intended to change

**Comment by 3dgiordano** [comment]
@undera sorry, I was making changes to a private repository branch that hadn't been resolved and I didn't think it was linked to this PR. 
Can you close this PR?
I don't have permission over this PR.
I'm going to release a new branch with the fix in another clean branch/PR.
Apologies for the inconvenience.

**Comment by 3dgiordano** [comment]
The new PR with fixes
https://github.com/undera/jmeter-plugins/pull/550

Please, ignore and close the actual PR #545

**Pull request closed without merging**
