### PR TITLE
Add Maven information to Plugin Card 

### PR DESCRIPTION
**Pull request by pmouawad**
This PR implements add the Maven information on the plugin card on website.
I don't know how to test if locally but the javascript part was tested, not the rendering.

Regards
Philippe M. from UbikLoadPack Team

### CODE REVIEW

**Comment by pmouawad** [comment]
Hi @undera ,
Is this one OK for you ?
Thanks

**Comment by undera** [comment]
I tried locally, not satisfied how it looks. I'll work on plugin card display and will merge this change.

**Comment by undera** [comment]
Merging as-is, for future improvement.

**Comment by undera** [comment]
I have rearranged maven info on card.

**Comment by pmouawad** [comment]
Thanks, it’s better indeed.
But maybe the last version should be displayed instead of the oldest one.

Regards

**Comment by undera** [comment]
I did not change the way it parses the version. Feel free to alter the algorithm

**Pull request merged**
