### PR TITLE
Add If function

### PR DESCRIPTION
**Pull request by igreenfield**

### CODE REVIEW

**Comment by undera** [comment]
Thanks for contribution! Did you know that this idea lies for years in our roadmap? Now you can remove it from Roadmap wiki page as completed. Also, please add changelog record and document new function.
Refer to http://jmeter-plugins.org/wiki/DeveloperGuide/

**Comment by undera** [comment]
Note that "Created by" should be removed from the comments, according to developer guide.

**Comment by igreenfield** [comment]
Done

**Comment by undera** [comment]
Please, remove all "Created by" comments.
Please, make documentation example to use new function, not "substring".

**Comment by undera** [comment]
Please, remove done item from Roadmap wiki page.

**Comment by igreenfield** [comment]
Sorry forget this, fixed

**Comment by undera** [comment]
Awesome! Thanks for contribution.

**Pull request merged**
