### PR TITLE
Two ways to change the legend color.

### PR DESCRIPTION
**Pull request by eostermueller**
Hi,

These changes provide the end user with two different ways to change the color in the JMeterPlugin legend.
Here is one user that has asked for these changes, but I've seen a few others:

https://groups.google.com/forum/#!topic/jmeter-plugins/pct5N5DX6IE

The first way to change the legend color is just to double click on the color box in the legend, which invokes the JP algorithm to chose the 'next color'.

The second way allows the users to indicate the color they would like for certain label text, as specified in the user.properties file.  For details, check the doc I provided.

Thanks,
--Erik

### CODE REVIEW

**Comment by undera** [comment]
Changelog record is missing, please add it

**Comment by eostermueller** [comment]
done, also updated Contributors.wiki.

**Comment by eostermueller** [comment]
Andrey, I just found a bug and fixed it.  Be sure to grab the commit with
the following comment.


Eriks-MBP:common erikostermueller$ git add
src/kg/apc/jmeter/graphs/AbstractGraphPanelVisualizer.java

Eriks-MBP:common erikostermueller$ git commit -m "fixed bug setting color
with Active Threads and Composite."


https://github.com/eostermueller/jmeter-plugins/commit/76299a2bb2266f2335dfd8325a0d497124756a4a

--Erik

**Comment by undera** [comment]
Thanks, I'll review it as soon as I'll have spare time

**Comment by undera** [comment]
Thanks for contributing!

**Comment by eostermueller** [comment]
Sure thing, I use jp most every day of the week.  The great usability, auto-scaling and other graphing features are better than any commercial software I've seen.

**Pull request merged**
