### PR TITLE
Add SynthesisReportGui and AggregateReportGui and allow generation of both CSV and PNG

### PR DESCRIPTION
**Pull request by pmouawad**
Hi @undera ,
Find here a PR that adds:
- SynthesisReportGui + AggregateReportGui generation as I find myself needing them nearly every time
- Adds BOTH to allow generation at the same time of CSV and PNG 

Hope you can take it into account soon.
Regards
Philippe M.
@philmdot

### CODE REVIEW

**Comment by undera** [comment]
Hi,

Thanks for contributing! 

I'm sorry, but I missed some things to ask from you when you initially contributed SynthesisReport (I was too excited to remember the rules). The rules are listed here: http://jmeter-plugins.org/wiki/DeveloperGuide/

In general, I miss unit tests (see coverage report here: http://jmeter-plugins.org/files/coverage/extras/, the only part that misses coverage at all is SynthesisReport), also a Changelog record and documentation changes. 

Please fill this gaps and I'll be happy to merge this PR

**Comment by pmouawad** [comment]
Hi Andrei,
As you can see from my PR, I am not creator of SynthesisReport. 
In my PR I am only adding it to the GraphGeneratorListener.

I will create a new PR with Changelog.wiki updated as long as docs.
Regards

**Comment by undera** [comment]
Ah, sorry then.
You don't need to create new PR, you can just add more commits to existing, GitHub handles this autommatically.

**Comment by pmouawad** [comment]
Hi,
I created 
https://github.com/undera/jmeter-plugins/pull/78

Regards

**Pull request closed without merging**
