### PR TITLE
Add textfields for phantomjs.cli.args and phantomjs.ghostdriver.args …

### PR DESCRIPTION
**Pull request by vdaburon**
…and send this parameters to PhantomJSDriver.

### CODE REVIEW

**Comment by undera** [comment]
Great to have this improvement. As usual it requires: unit tests, changelog record, documentation update

**Comment by vdaburon** [comment]
Modify documentation for PhantomJS WebDriver GUI

**Comment by undera** [comment]
Please, cover your additions with unit tests. The project relies on unit tests very much...

**Comment by undera** [comment]
I'm forcing merge

**Pull request merged**
