### PR TITLE
__strReplaceRegex instead of __strReplace

### PR DESCRIPTION
**Pull request by jloisel**
Key of the StrReplaceRegex function seems incorrect, it should be "__strReplaceRegex", not "__strReplace".

### CODE REVIEW

**Comment by undera** [comment]
The function name would have to remain the same for the historical reasons. It was like that in the beginning and cannot change in a breaking way now.

**Comment by jloisel** [comment]
The function is not working at all due to to wrong name (which is already used by another one). You're not breaking anything since it's already broken.

**Comment by jloisel** [comment]
`__strReplace` and `__strReplaceRegex` have both the same key `__strReplace`.

**Comment by undera** [comment]
Wow, that changes everything. Thanks for reporting this!

**Comment by undera** [comment]
New version has been released, thanks for being persistent

**Pull request merged**
