### PR TITLE
CorrealtionRecorder Plugin v1.0

### PR DESCRIPTION
**Pull request by Baraujo25**

### CODE REVIEW

**Comment by sginsbourg** [comment]
Is there some documentation for the correlation recorder plugin?

**Comment by QAInsights** [comment]
@sginsbourg Please check this link https://github.com/Blazemeter/CorrelationRecorder/blob/master/README.md

**Comment by Baraujo25** [comment]
Hello,

Yes, you can visualize the README of the plugin on the plugin manager frame. Also [**_here_**](https://github.com/Blazemeter/CorrelationRecorder#correlations-recorder-plugin-for-jmeter) you can find more documentation regarding the *Correlation Recorder* plugin.

We have done some modifications in the last minute (adding some dependencies) I recommend you to update if you have beforehand downloaded it :wink:

We are more than welcome to receive feedback from the plugin, also, feel free to ask for more information!

**Comment by QAInsights** [comment]
@Baraujo25 Just started the testing, will keep you informed :)

**Pull request merged**
