### PR TITLE
Added DI-Kafkameter plugin

### PR DESCRIPTION
**Pull request by rollno748**

### CODE REVIEW

**Comment by undera** [comment]
Please remove all the changes that are irrelevant to your plugin. The change has to only contain lines related to your plugin.

**Comment by undera** [comment]
Also, the download URL has resulted in 404, thus the Travis build has failed. This also needs to be fixed.

**Comment by rollno748** [comment]
Hello Andrey,

Thanks for the information. will update the change accordingly



Thanks,
Mohamed Ibrahim

**Comment by rollno748** [comment]
Hello Andrey,

I have fixed all the issues with the merge. Still, it's failing for me.
Can you please take a look and advise ?

https://github.com/undera/jmeter-plugins/pull/478



Thanks,
Mohamed Ibrahim

**Pull request closed without merging**
