### PR TITLE
New version of plugins for CI/CD integration

### PR DESCRIPTION
**Pull request by rbourga**
Adding new versions of plugins for command line interface (CLI) execution in a Continuous Integration/Delivery pipelines.

### CODE REVIEW

**Comment by rbourga** [comment]
Hi Andrey,

I am still not seeing the new versions of the plugin in the Plugin Manager.
How long do we have to wait for them to be listed?

Thanks,
Robert


Le mer. 2 mars 2022 à 17:43, Andrey Pokhilko ***@***.***> a
écrit :

**Comment by sginsbourg** [comment]
Hi,

Thank you for the update.

I'm looking for a list of features and contents of this plugin.

Is there any documentation to read?

Regards,
Shay

**Comment by undera** [comment]
Fixed the build. Thanks for letting me know that it was broken.

**Comment by rbourga** [comment]
Great, thanks!
All good now!

Le jeu. 3 mars 2022 à 19:20, Andrey Pokhilko ***@***.***> a
écrit :

**Pull request merged**
