### PR TITLE
Fixed permission-denied-error on unix systems in LoadosophiaUploader

### PR DESCRIPTION
**Pull request by dimitrijber**
When a plugin is used to run on multiple environments, it is sometimes preferable that the storeDir is set to the system's default temp directory. I tried out not to set storeDir at all, but then i got a "premission denied" error because the code tries to set an trailing slash to an empty string resulting in "/" which is then passed to File.createTempFile("Loadosophia_", ".jtl", new File("/")); which results in an temp-file in the root directory. If run with unprivileged user, it will fail to create that file.

Why is it necessary to set storeDir? Why don't you use the system's temp folder in all cases?

### CODE REVIEW

**Comment by undera** [comment]
Changelog record is missing, according to http://jmeter-plugins.org/wiki/DeveloperGuide/

**Comment by undera** [comment]
Setting store dir is important. For example, some systems have very limited temporary directory space, so they will need a way to change the place to store intermediary data.

**Comment by dimitrijber** [comment]
Oh, sorry, I should have better first read the DevGuide :-) It's done now.

**Comment by undera** [comment]
Thanks!

**Pull request merged**
