### PR TITLE
Expose the duration of RPS which is sum of the last column Duration

### PR DESCRIPTION
**Pull request by pmouawad**
As per discussion:

https://groups.google.com/forum/#!searchin/jmeter-plugins/Throughput$20Shaping$20Timer$20$2F$20enhancements%7Csort:date/jmeter-plugins/U456alfPNBs/0YnJU0zJAAAJ

Regards
Philippe M.
@philmdot

UbikLoadPack Team

### CODE REVIEW

**Comment by undera** [comment]
Thanks!

**Comment by pmouawad** [comment]
Thanks for merging.
Is there a short term plan to release a version ? thanks

**Comment by pmouawad** [comment]
Hi Andrey,
In this case, for now I have no further changes planned.

Regards

**Comment by undera** [comment]
Version 2.2 with your changes has been released. Thanks for contributing!

**Pull request merged**
