### PR TITLE
Enhance webdriver

### PR DESCRIPTION
**Pull request by pmouawad**
This PR adds usual scripting variables:
WDS.vars
WDS.ctx
WDS.props

And allows to not override particular response code

Regards
Philippe M. from UbikLoadPack team

### CODE REVIEW

**Comment by undera** [comment]
Looks good!

**Comment by undera** [comment]
I have released webdriver plugin with changes

**Comment by pmouawad** [comment]
Thanks @undera,
It doesn’t appear yet on search in jmeter-plugins, is it regular ?

Thanks

**Comment by undera** [comment]
It might take a bit of time to publish on the website

**Comment by undera** [comment]
When plugin download is hosted on maven it takes time first to appear on maven and then some time for website to update. It's an automated process. 
When download is hosted on GitHub, it's much faster, since there is no "wait for maven" stage.

**Comment by undera** [comment]
FYI I have also pushed Plugins Manager update into publishing queue.

**Comment by undera** [comment]
All of changes have reached the website now.

**Pull request merged**
