### PR TITLE
Version 2.1.1 - ElasticSearch Backend Listener

### PR DESCRIPTION
**Pull request by delirius325**
* Added use of assertionArray
* getElapsedTime now returns a generic date for comparison in Jenkins AND the elapsed time according to today.
* Added "sentBytes" metric
* ResponseTime uses the getTime() method
* Added timeout to avoid hanging requests
* Corrected formatting of dates
* Added logging in case of failures

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello,
Is there a reason for now merging the PR ?

Thanks
Regards

**Comment by undera** [comment]
There is merge conflict, can you please review and fix it?

**Comment by undera** [comment]
@pmouawad I just was on vacation, traveling. Now I'm back and reviewing the pending PRs

**Comment by pmouawad** [comment]
Hello,
Although PR has been merged, version 2.1.1 does not appear as available on jmeter-plugins, neither 2.0.2, 2.1.0.

Is there an issue ?
Thanks

**Comment by undera** [comment]
Yes, there was an issue with deploy process, it is fixed now. Your plugin should be available.

**Pull request merged**
