### PR TITLE
Setting Java compliance level to 1.8

### PR DESCRIPTION
**Pull request by rbourga**
So that users running Java JRE 1.8 can execute the plugin.

### CODE REVIEW

**Comment by undera** [comment]
You will need to resolve conflicts

**Comment by rbourga** [comment]
Hi Andy,
I have reolved conflict. Can you merge my changes please?
Thanks.

**Comment by undera** [comment]
I'm sorry, but in current state, JSON gets broken. You probably placed some brackets wrong. Please fix the structure of JSON.

**Comment by rbourga** [comment]
Canyou try again please - have made some changes. Thx.

**Comment by undera** [comment]
Looks OK now

**Comment by rbourga** [comment]
Cool, thanks!

Le jeu. 4 févr. 2021 à 22:51, Andrey Pokhilko <notifications@github.com> a
écrit :

**Pull request merged**
