### PR TITLE
Correlation Recorder v1.2.3

### PR DESCRIPTION
**Pull request by 3dgiordano**
- Improved compatibility with new versions of JMeter
- Compatibility problems with MS Windows are solved

### CODE REVIEW

**Comment by undera** [comment]
I have created an issue on their support forum: https://travis-ci.community/t/unable-to-set-up-php-5-6-with-phpenv/13592

**Comment by 3dgiordano** [comment]
Looking at the logs, I see that the new images do not have pre-installed the versions that they indicate to have

Preinstalled PHP versions on the actual docker image of travis ci (Xenial)
  7.4
* 7.4.30 (set by /home/travis/.phpenv/version)

Some days ago (Xenial)
  5.6
  5.6.40
  7.1
  7.1.27
  7.2
* 7.2.15 (set by /home/travis/.phpenv/version)

In both cases it uses the Xenial distribution, but it seems that the latest version does not have those pre-installed versions.

**Comment by undera** [comment]
Plugins website needs PHP 5.6 to work properly. The fact that TravisCI have broken the compatibility with older versions, while their docs still promise those versions -- overall very sad.

**Comment by undera** [comment]
Or we need to find a way to configure the build to install PHP 5.6 from some PPA

**Comment by pmouawad** [comment]
Hello @undera , 
Would witching to an up to date PHP version be too much work  for the website ?
5.6 is in EOL since many years so it can explain why Travis CI stopped supporting it.

Thanks

**Comment by undera** [comment]
The hosting we use has quite old platform with PHP 5.6. It would be a lot of trouble to reinstall everything including OS. I'd rather change Travis for something else...

**Pull request merged**
