### PR TITLE
Common base class for all monitoring plugins

### PR DESCRIPTION
**Pull request by tilln**
Several existing plugins such as JMXMon, DbMon, Perfmon use a common pattern for building the GUI as well as using a Collector class with a worker thread for collecting the monitoring samples (which use the Response Message field for the queried value).
This pattern should be generalized so that the above as well as future monitoring plugins can inherit the common behavior.
This pull request just adds those common classes (without refactoring existing plugins) for review by maintainers/contributors.

### CODE REVIEW

**Comment by undera** [comment]
16 codacy warnings have to be addressed

**Comment by undera** [comment]
Also, there are chunks of uncovered code, which look like important. Especially for infra part.

**Comment by tilln** [comment]
I'm aware of the coverage/warning issues. However, these come from existing code I'm proposing this refactoring for, unfortunately. 
If I had more time, I'd re-write the unit tests as well, but at this stage all I've done is pull up the common code into a common parent, including the (poor) test code.

**Comment by undera** [comment]
Thanks! Let's proceed

**Pull request merged**
