### PR TITLE
 UbikLoadPack Video Streaming plugin Release 7.1.2

### PR DESCRIPTION
**Pull request by ubikloadpack**
Hello @undera ,
This PR is to publish a new version of UbikLoadPack Video Streaming plugin.

Thank you in advance for your help.
Regards
UbikLoadPack Team

### CODE REVIEW

**Comment by ubikloadpack** [comment]
Thank you for merging rapidly.
For now it seems 7.1.2 is not visible on jmeter-plugins, is there an issue ?
Thanks

**Comment by undera** [comment]
Sorry for the delay, it should be fixed now

**Comment by ubikloadpack** [comment]
Thanks @undera ,
but for now I still see only 7.1.1 .
Regards

**Comment by undera** [comment]
I've queried http://jmeter-plugins.org/repo/ and I see 7.1.2 descriptor is there

**Comment by ubikloadpack** [comment]
Yes now looks good on my end.
But it seems there may be some caching issue maybe as it is not ok from everywhere. 
Thanks a lot for your reactivity anyway.

**Pull request merged**
