### PR TITLE
jpgc-webdriver: addition of webdriver for Edge and upgrade to Selenium 4.7.2

### PR DESCRIPTION
**Pull request by rbourga**
Update to jpgc-webdriver plugin.

### CODE REVIEW

**Comment by undera** [comment]
I have published the JAR into maven, but actually CI complains that `opentelemetry-sdk-common` is not downloadable. I wonder why we need that library at all...

**Comment by rbourga** [comment]
Hi Andrey,
Thanks for the merge.
However, plugin manager is still showing version 4.6.0 for the Selenium
plugin instead of 4.7.2.
How long must we wait before 4.7.2 appears online?
Thanks.

Le lun. 19 déc. 2022 à 16:02, Andrey Pokhilko ***@***.***> a
écrit :

**Comment by undera** [comment]
It's already there: https://jmeter-plugins.org/?search=jpgc-webdriver

**Comment by undera** [comment]
Don't forget there is local repo caches in pmgr

**Comment by rbourga** [comment]
All good now, I can see 4.7.2 from Plugin Manager.
I will post a message on Linkedin JMeter group to inform users of the new
driver for Edge.
Thank you Andrey.

Le lun. 19 déc. 2022 à 16:47, Andrey Pokhilko ***@***.***> a
écrit :

**Pull request merged**
