### PR TITLE
New version of wssecurity plugin

### PR DESCRIPTION
**Pull request by tilln**

### CODE REVIEW

**Comment by undera** [comment]
Hi,
There is "changes" field for version item, it is good practice to write that what's new to clarify for users the need to upgrade. Do yo want to add it?

**Comment by undera** [comment]
Great, thanks!

**Comment by tilln** [comment]
How about the (binary) zip packages? Would you still provide them? (Are they generated automatically?)

**Comment by undera** [comment]
ZIP packages are generated by Jenkins that publishes website. It will recognize this situation fine.

**Pull request merged**
