### PR TITLE
Add Jmeter Prometheus plugin

### PR DESCRIPTION
**Pull request by GiovanniPaoloGibilisco**
Add Jmeter prometheus plugin as suggested here: https://github.com/johrstrom/jmeter-prometheus-plugin/issues/82

I've removed markerClass and componentClasses from the same as I'm not sure what they should refer to.

### CODE REVIEW

**Comment by undera** [comment]
It's almost good. Please provide in `vendor` whatever name you like - it may be your company name, or your full name, or your nickname.
Also, you have to provide `markerClass` - it's a full Java class name of your main component, used to identify presence of plugin in Java classpath. In your plugin, `com.github.johrstrom.collector.SuccessRatioCollector` seem to be a valid option.

**Comment by undera** [comment]
`componentClasses` list all of test elements in your plugin. This field is used for nice feature when use opens JMX file on a machine without your plugin, and plugin manager offers to install missing plugin. This field is optional, you can omit it.

**Comment by GiovanniPaoloGibilisco** [comment]
I've added the vendor, marker and component classes

**Comment by undera** [comment]
Looks good now. I'm merging it.
When you have new releases of your plugin, please consider creating another PR, adding new version to `versions` section.
Thanks for contributing!

**Pull request merged**
