### PR TITLE
Fixing of HelpLink and of jar version

### PR DESCRIPTION
**Pull request by rbourga**
Alignment of version number in various.json with version number of jar file.
Fix of url in "Help on this plugin" link in UI .

### CODE REVIEW

**Comment by undera** [comment]
You should merge current master branch into your branch, to resolve the conflict.

**Comment by rbourga** [comment]
Hi Andrey,
sorry for the conflict, I have a little difficulty in resolving this
conflict.
Would you have any ideas to help, the ones on Google are confusing as well!
Thanks.


Le ven. 22 janv. 2021 à 15:07, Andrey Pokhilko <notifications@github.com> a
écrit :

**Comment by undera** [comment]
I can't say I'm better than answers on Google. This guide is very good IMO: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by undera** [comment]
Looks good

**Comment by rbourga** [comment]
Awesome, thanks!

Le ven. 22 janv. 2021 à 18:56, Andrey Pokhilko <notifications@github.com> a
écrit :

**Pull request merged**
