### PR TITLE
Try to cleanly stop threads before doing it abruptly to avoid pending samplers being interrupted

### PR DESCRIPTION
**Pull request by pmouawad**
Currently in logs we have:

2018-03-09 11:45:58,017 ERROR k.a.j.t.VariableThroughputTimer: Waiting thread was interrupted
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[?:1.8.0_131]
	at kg.apc.jmeter.timers.VariableThroughputTimer.delay(VariableThroughputTimer.java:98) [jmeter-plugins-tst-2.2.jar:?]
	at org.apache.jmeter.threads.JMeterThread.delay(JMeterThread.java:857) [ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:472) [ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:416) [ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250) [ApacheJMeter_core.jar:4.0 r1823414]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Which is disturbing.

### CODE REVIEW

**Comment by pmouawad** [comment]
Thanks for merging.
Do you think you can release a new version soon ?

Thank you

**Comment by undera** [comment]
Is this change as critical so it worth release? Looks like quite minor change...

**Comment by pmouawad** [comment]
It is not that minor.
I was initially looking for a clean shutdown of threads, but currently what happens is that:
- it is still not clean as it interrupts threads and pending samplers leading to artificial errors
- it logs a ton of error messages

Regards

**Comment by undera** [comment]
It's not a big issue to release, but I'd like to minimize disturbance for users by too minor releases. Is there a chance you will test it with your cases more and probably other improvements will arise?

**Comment by undera** [comment]
If you are 100% sure no other improvements will happen soon - I'll release it.

**Comment by pmouawad** [comment]
Hello Andrey,
Version was tested and it answers correctly requirement now.
I expect no further improvements in short future (2 months at least :-) ).
Regards

**Comment by undera** [comment]
Released. Should appear online soon

**Pull request merged**
